### ISSUE TITLE
Build instruction improvements

### ISSUE THREAD

**Issue by keinstein** [francesco-kriegel/conexp-fx#3]
Hi Francesco,

would it be possible to explain, how I can build conexp-fx on a standard debian distribution?
The problem is to get the dependencies right. At first installing java-fx is not straight forward. After installing the openjfx and openjfx-sources packages I got some strange error message, but in the next run the preparation of JavaFX seemed to work but it is still complaining about the missing maven plugin, which I cannot build for some other missing package I don't know where to get. 

Web start is nice, but not an option for everyday work as I'm not always online. Btw. it seems to be broken on your home page.

**Comment by francesco-kriegel** [comment]
Hi Tobias,

Sure, I can help you to successfully compile my project.  First of all, I want to clarify that I am always developing, testing, and running the project with the Oracle JDK, currently version 8.  New features are programmed using Scala 2.11 instead of Java.  This does not cause any problems, since interoperation between both languages is easily possible.  Consequently, I suggest you to use the Oracle JDK, which also includes Oracle's implementation of JavaFX, instead of any other JDK like OpenJDK.

Regarding the missing packages, can you please specify which exactly are claimed as missing?  You can, e.g., simply post a screen capture.  Have you already executed the steps which I explain under [https://github.com/francesco-kriegel/conexp-fx#installation-of-non-maven-dependencies-and-javafx-javadoc-and-javafx-source-to-local-maven-repository](https://github.com/francesco-kriegel/conexp-fx#installation-of-non-maven-dependencies-and-javafx-javadoc-and-javafx-source-to-local-maven-repository)?  The suggested command `mvn validate -Pinstall-dependencies` installs the dependencies from the `lib` folder.  Furthermore, when running the Maven goal `package` the Maven plugin `javafx-maven-plugin` is necessary, from which I created a fork and adjusted according to my needs.  You can find this Maven plugin on my GitHub account under [https://github.com/francesco-kriegel/javafx-maven-plugin](https://github.com/francesco-kriegel/javafx-maven-plugin).  Please clone it, and install it with Maven, i.e., switch to the parent directory of the directory in which you cloned `conexp-fx`, run the command `git clone git@github.com:francesco-kriegel/javafx-maven-plugin.git`, then `cd javafx-maven-plugin`, and finally `mvn install`.  You should possibly execute similar commands for the other dependency `fcalib`, which is available under [https://github.com/julianmendez/fcalib](https://github.com/julianmendez/fcalib).

Please tell me whether these steps helped you to resolve the building issue.  If not, then please drop me a line again.  Thanks in advance!

Cheers,
Francesco
